variables:
  GOCACHE: $CI_PROJECT_DIR/.go-build

cache:
  key: "$CI_PROJECT_PATH $CI_BUILD_REF_NAME"
  paths:
    - .go-build

stages:
  - lint
  - build
  - test

lint:
  stage: lint
  image: registry.furqansoftware.net/cardboard/staticcheck:0.7.0-1
  script:
    - staticcheck ./...

build:
  stage: build
  image: registry.furqansoftware.net/cardboard/golang:1.26.1-bullseye-0
  script:
    - go build ./...

test:
  stage: test
  image: registry.furqansoftware.net/cardboard/golang:1.26.1-bullseye-0
  needs:
    - build
  script:
    - go test -race $(go list ./... | grep -v /vendor/)
